[common]
; Don't use quotation marks in path!
default_bnk_path=

; Default values are: DefaultTheme.css, TransparentTheme.css, system, none.
; no value is equivalent to using DefaultTheme.css.
; You can define more themes in the AppData/advisual (win), or .config/advisual (linux) folder.
theme_name=

[common_shortcuts]
show_help=F1
show_settings=F2
continue_playback=space
restart_playback=<Shift>space
load=<Ctrl>l
save=<Ctrl>s
quit=<Ctrl>q

[composer_shortcuts]
cut_selection=<Ctrl>x
copy_selection=<Ctrl>c
paste_selection=<Ctrl>v
erase_selection=BackSpace
move_selection_semitone_up=Up
move_selection_semitone_down=Down
move_selection_tick_left=Left
move_selection_tick_right=Right
move_selection_measure_left=<Alt>Left
move_selection_measure_right=<Alt>Right
unselect=Escape
undo=<Ctrl>z
redo=<Ctrl><Shift>z
toggle_insert_mode=Insert
