[common]
; Don't use quotation marks in paths!
default_bnk_path=

; Edit theme_path with caution, it could crash advisual!
; Empty theme_path means default style.
theme_path=

[common_shortcuts]
show_help=F1
show_settings=F2
continue_playback=space
restart_playback=<Shift>space
load=<Ctrl>l
save=<Ctrl>s
quit=<Ctrl>q

[composer_shortcuts]
cut_selection=<Ctrl>x
copy_selection=<Ctrl>c
paste_selection=<Ctrl>v
erase_selection=BackSpace
move_selection_semitone_up=Up
move_selection_semitone_down=Down
move_selection_tick_left=Left
move_selection_tick_right=Right
move_selection_measure_left=<Alt>Left
move_selection_measure_right=<Alt>Right
unselect=Escape
undo=<Ctrl>z
redo=<Ctrl><Shift>z