/*
 * Adplug - Replayer for many OPL2/OPL3 audio file formats.
 * Copyright (C) 1999 - 2008 Simon Peter, <dn.tlp@gmx.net>, et al.
 * Copyright (C) 2026 Robert McDowell, GitHub(@RobertP-McDowell)
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Forked from adplug:
 * composer.h - AdLib Visual Composer synth class by OPLx <oplx@yahoo.com>
 *              with improvements by Stas'M <binarymaster@mail.ru> and Jepael
 * Forked to AdVisual:
 * VisPlayer.h - AdVisual synth class, modifications by GitHub(@RobertP-McDowell).
 *
 * Source references ADLIB.C from Adlib MSC SDK.
 */
#include <cstring>
#include <algorithm>
#include <binstr.h>

#include "VisPlayer.h"
#include <common.h>

//---------------------------------------------------------
static int16_t  const skNrStepPitch          = 25; // 25 steps within a half-tone for pitch bend
static uint8_t  const skMaxNotes             = 96U;
static uint8_t  const skCarrierOpOffset      = 3U;
static uint8_t  const skNumSemitonesInOctave = 12U;
//---------------------------------------------------------
static uint8_t const skOPL2_WaveCtrlBaseAddress      = 0x01U; // Test LSI / Enable waveform control
static uint8_t const skOPL2_AaMultiBaseAddress       = 0x20U; // Amp Mod / Vibrato / EG type / Key Scaling / Multiple
static uint8_t const skOPL2_KSLTLBaseAddress         = 0x40U; // Key scaling level / Operator output level
static uint8_t const skOPL2_ArDrBaseAddress          = 0x60U; // Attack Rate / Decay Rate
static uint8_t const skOPL2_SlrrBaseAddress          = 0x80U; // Sustain Level / Release Rate
static uint8_t const skOPL2_FreqLoBaseAddress        = 0xA0U; // Frequency (low 8 bits)
static uint8_t const skOPL2_KeyOnFreqHiBaseAddress   = 0xB0U; // Key On / Octave / Frequency (high 2 bits)
static uint8_t const skOPL2_AmVibRhythmBaseAddress   = 0xBDU; // AM depth / Vibrato depth / Rhythm control
static uint8_t const skOPL2_FeedConBaseAddress       = 0xC0U; // Feedback strength / Connection type
static uint8_t const skOPL2_WaveformBaseAddress      = 0xE0U; // Waveform select
//---------------------------------------------------------
static uint8_t const skOPL2_EnableWaveformSelectMask = 0x20U;
static uint8_t const skOPL2_KeyOnMask                = 0x20U;
static uint8_t const skOPL2_RhythmMask               = 0x20U;
static uint8_t const skOPL2_KSLMask                  = 0xC0U;
static uint8_t const skOPL2_TLMask                   = 0x3FU;
static uint8_t const skOPL2_TLMinLevel               = 0x3FU;
static uint8_t const skOPL2_FNumLSBMask              = 0xFFU;
static uint8_t const skOPL2_FNumMSBMask              = 0x03U;
static uint8_t const skOPL2_FNumMSBShift             = 0x08U;
static uint8_t const skOPL2_BlockNumberShift         = 0x02U;
//---------------------------------------------------------
static uint8_t const skNoteOctave[skMaxNotes] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
};
//---------------------------------------------------------
static uint8_t const skNoteIndex[skMaxNotes] =
{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
};
//---------------------------------------------------------
// Table below generated by initialize_fnum_table function (from Adlib Music SDK).
static uint16_t const skFNumNotes[skNrStepPitch][skNumSemitonesInOctave] =
{
	343, 364, 385, 408, 433, 459, 486, 515, 546, 579, 614, 650,
	344, 365, 387, 410, 434, 460, 488, 517, 548, 581, 615, 652,
	345, 365, 387, 410, 435, 461, 489, 518, 549, 582, 617, 653,
	346, 366, 388, 411, 436, 462, 490, 519, 550, 583, 618, 655,
	346, 367, 389, 412, 437, 463, 491, 520, 551, 584, 619, 657,
	347, 368, 390, 413, 438, 464, 492, 522, 553, 586, 621, 658,
	348, 369, 391, 415, 439, 466, 493, 523, 554, 587, 622, 660,
	349, 370, 392, 415, 440, 467, 495, 524, 556, 589, 624, 661,
	350, 371, 393, 416, 441, 468, 496, 525, 557, 590, 625, 663,
	351, 372, 394, 417, 442, 469, 497, 527, 558, 592, 627, 665,
	351, 372, 395, 418, 443, 470, 498, 528, 559, 593, 628, 666,
	352, 373, 396, 419, 444, 471, 499, 529, 561, 594, 630, 668,
	353, 374, 397, 420, 445, 472, 500, 530, 562, 596, 631, 669,
	354, 375, 398, 421, 447, 473, 502, 532, 564, 597, 633, 671,
	355, 376, 398, 422, 448, 474, 503, 533, 565, 599, 634, 672,
	356, 377, 399, 423, 449, 475, 504, 534, 566, 600, 636, 674,
	356, 378, 400, 424, 450, 477, 505, 535, 567, 601, 637, 675,
	357, 379, 401, 425, 451, 478, 506, 537, 569, 603, 639, 677,
	358, 379, 402, 426, 452, 479, 507, 538, 570, 604, 640, 679,
	359, 380, 403, 427, 453, 480, 509, 539, 571, 606, 642, 680,
	360, 381, 404, 428, 454, 481, 510, 540, 572, 607, 643, 682,
	360, 382, 405, 429, 455, 482, 511, 541, 574, 608, 645, 683,
	361, 383, 406, 430, 456, 483, 512, 543, 575, 610, 646, 685,
	362, 384, 407, 431, 457, 484, 513, 544, 577, 611, 648, 687,
	363, 385, 408, 432, 458, 485, 514, 545, 578, 612, 649, 688
};
//---------------------------------------------------------
static uint8_t const drum_op_table[4] = { 0x14, 0x12, 0x15, 0x11 };
//---------------------------------------------------------
int   const CVisPlayer::kSizeofDataRecord    = 30;
int   const CVisPlayer::kSilenceNote         = -12;
int   const CVisPlayer::kNumMelodicVoices    = MAX_VOICES - 2;
int   const CVisPlayer::kNumPercussiveVoices = MAX_VOICES;
int   const CVisPlayer::kBassDrumChannel     = 6;
int   const CVisPlayer::kSnareDrumChannel    = 7;
int   const CVisPlayer::kTomtomChannel       = 8;
int   const CVisPlayer::kTomTomNote          = 24;
int   const CVisPlayer::kTomTomToSnare       = 7; // 7 half-tones between voice 7 & 8
int   const CVisPlayer::kSnareNote           = CVisPlayer::kTomTomNote + CVisPlayer::kTomTomToSnare;
//---------------------------------------------------------
uint32_t const CVisPlayer::kMidPitch         = 0x2000U;
uint8_t  const CVisPlayer::kMaxVolume        = 0x7FU;

/*** public methods **************************************/
CVisPlayer::CVisPlayer(Copl* p_opl, Track* p_track, Bank* p_bank) : CPlayer(p_opl),
		track(p_track), bank(p_bank), tick(0),
		mFNumFreqPtrList(kNumPercussiveVoices, skFNumNotes[0]), mpOldFNumFreqPtr(NULL),
		mHalfToneOffset(kNumPercussiveVoices, 0), mVolumeCache(kNumPercussiveVoices, kMaxVolume),
		mKSLTLCache(kNumPercussiveVoices, 0), mNoteCache(kNumPercussiveVoices, 0),
		mKOnOctFNumCache(kNumMelodicVoices, 0), mKeyOnCache(kNumPercussiveVoices, false),
		mOldPitchBendLength(~0), mPitchRangeStep(skNrStepPitch), mOldHalfToneOffset(0), mAMVibRhythmCache(0) {
	refresh_rate = track->basic_tempo;
	mRhythmMode = !track->melodic_mode;
	dynamic_notes.fill(-1);
}
//---------------------------------------------------------
CPlayer* CVisPlayer::factory(Copl* p_opl, Track* p_track, Bank* p_bank) {
	if (p_track == nullptr) {
		cerr << "Error initializing CVisPlayer, p_track is nullptr\n";
		return nullptr;
	}
	if (p_bank == nullptr) {
		cerr << "Error initializing CVisPlayer, p_bank is nullptr\n";
		return nullptr;
	}
	return new CVisPlayer(p_opl, p_track, p_bank);
}
//---------------------------------------------------------
void CVisPlayer::refresh_track_events() {
	int tempo_tick; // Reset properties to last events.
	float tempo_value;
	track->get_last_tempo_event(tick, tempo_tick, tempo_value);
	refresh_rate = (track->ticks_per_beat * track->basic_tempo * tempo_value) / 60.0f;
	for (int v = 0; v < get_channel_count(); v++) {
		refresh_voice_events(v);
	}
}
void CVisPlayer::refresh_voice_events(int v) {
	Channel* channel = track->get_channel(v);
	int ins_tick, pitch_tick, volume_tick;
	float pitch_value, volume_value;
	string ins_value;
	channel->get_last_instrument_event(tick, ins_tick, ins_value);
	channel->get_last_pitch_event(tick, pitch_tick, pitch_value);
	channel->get_last_volume_event(tick, volume_tick, volume_value);
	Instrument* instrument = bank->find_instrument(ins_value);
	if (instrument == nullptr) {
		cerr << "Channel " << v << " Couldn't find instrument of name " << ins_value << "\n";
		set_instrument(v, &Instrument::default_instrument);
	}
	else {
		set_instrument(v, instrument);
	}
	set_volume(v, uint8_t(kMaxVolume * volume_value));
	change_pitch(v, ( pitch_value == 1.0f ? kMidPitch : uint16_t((0x3fff >> 1) * pitch_value) ));
}
//---------------------------------------------------------
void CVisPlayer::enable_channel(int v) {
	if (v >= get_channel_count()) {
		return;
	}
	note_off(v);
	dynamic_notes[v] = -1;
	refresh_voice_events(v);
}
//---------------------------------------------------------
void CVisPlayer::channel_play_note(int channel, int note_pitch, Instrument* instrument, float pitch_mult, float volume_mult) {
	if (channel >= get_channel_count()) {
		cerr << "disable_channel_and_play_note() voice " << channel << " >= " << get_channel_count() << "\n";
		return;
	}
	if (note_pitch <= -1) { // Let the channel play as normal.
		note_off(channel);
		dynamic_notes[channel] = -1;
		return;
	}
	if (note_pitch == 0) { // 0 still overrides the notes on the channel, but doesn't play anything.
		note_off(channel);
	}
	else if (note_pitch > 0) { // Anything above 0 will play sound like a normal note.
		if (instrument != nullptr) {
			set_instrument(channel, instrument);
		}
		set_volume(channel, uint8_t(kMaxVolume * volume_mult));
		change_pitch(channel, ( pitch_mult == 1.0f ? kMidPitch : uint16_t((0x3fff >> 1) * pitch_mult) ));
		note_on(channel, 107 - note_pitch);
	}
	dynamic_notes[channel] = note_pitch;
}
//---------------------------------------------------------
void CVisPlayer::enable_all_channels() {
	for (int v = 0; v < kNumPercussiveVoices; v++) {
		dynamic_notes[v] = -1;
		note_off(v);
	}
}
//---------------------------------------------------------
void CVisPlayer::disable_all_channels() {
	for (int v = 0; v < kNumPercussiveVoices; v++) {
		dynamic_notes[v] = 0;
		note_off(v);
	}
}
//---------------------------------------------------------
void CVisPlayer::update_voice(int v) {
	Channel* channel = track->get_channel(v);
	int ins_tick, pitch_tick, volume_tick;
	float pitch_value, volume_value;
	string ins_value;
	channel->get_last_instrument_event(tick, ins_tick, ins_value);
	channel->get_last_pitch_event(tick, pitch_tick, pitch_value);
	channel->get_last_volume_event(tick, volume_tick, volume_value);

	if (ins_tick == tick) {
		Instrument* instrument = bank->find_instrument(ins_value);
		if (instrument == nullptr) {
			if (ins_tick == tick) {
				cerr << "Channel " << v << " Couldn't find instrument of name " << ins_value << "\n";
			}
			set_instrument(v, &Instrument::default_instrument);
		}
		else {
			set_instrument(v, instrument);
		}
	}
	if (volume_tick == tick) {
		set_volume(v, uint8_t(kMaxVolume * volume_value));
	}
	if (pitch_tick == tick) {
		change_pitch(v, ( pitch_value == 1.0f ? kMidPitch : uint16_t((0x3fff >> 1) * pitch_value) ));
	}

	Note* note_at_tick = channel->get_note_on_tick(tick);
	if (note_at_tick == nullptr) { // Turned off.
		if (channel->get_note_on_tick(tick-1) != nullptr) { // Just turned off.
			note_off(v);
		}
	}
	else if (note_at_tick->offset == tick) { // Turned on.
		note_on(v, 107 - note_at_tick->pitch);
	}
}

//---------------------------------------------------------
bool CVisPlayer::update_track() {
	int tempo_tick;
	float tempo_value;
	track->get_last_tempo_event(tick, tempo_tick, tempo_value);
	refresh_rate = (track->ticks_per_beat * track->basic_tempo * tempo_value) / 60.0f;
	for (int v = 0; v < get_channel_count(); v++) {
		if (dynamic_notes[v] != -1) {
			continue;
		}
		update_voice(v);
	}
	tick++;
	return true;
}
//---------------------------------------------------------
bool CVisPlayer::update() {
	return update_track();
}
//---------------------------------------------------------
void CVisPlayer::rewind(int subsong) {
	DBPRINT("Rewind from initial current position " << tick << " to " << subsong << "\n");
	tick = subsong;

	mHalfToneOffset  = TInt16Vector(kNumPercussiveVoices, 0);
	mVolumeCache     = TUInt8Vector(kNumPercussiveVoices, kMaxVolume);
	mKSLTLCache      = TUInt8Vector(kNumPercussiveVoices, 0);
	mNoteCache       = TUInt8Vector(kNumPercussiveVoices, 0);
	mKOnOctFNumCache = TUInt8Vector(kNumMelodicVoices, 0);
	mKeyOnCache      = TBoolVector(kNumPercussiveVoices, false);

	opl->init();         // initialize to melodic by default

	set_rhythm_mode(!track->melodic_mode);
	opl->write(skOPL2_WaveCtrlBaseAddress, skOPL2_EnableWaveformSelectMask); // Enable waveform select
	refresh_track_events();
}
//---------------------------------------------------------
int CVisPlayer::get_channel_count() const { return (mRhythmMode == 1 ? kNumPercussiveVoices : kNumMelodicVoices); }
//---------------------------------------------------------
void CVisPlayer::set_rhythm_mode(int const mode)
{
	if (mode)
	{
		mAMVibRhythmCache |= skOPL2_RhythmMask;
		opl->write(skOPL2_AmVibRhythmBaseAddress, mAMVibRhythmCache); // Enable rhythm mode

		set_freq(kTomtomChannel, kTomTomNote);
		set_freq(kSnareDrumChannel, kSnareNote);
	}
	else
	{
		mAMVibRhythmCache &= ~skOPL2_RhythmMask;
		opl->write(skOPL2_AmVibRhythmBaseAddress, mAMVibRhythmCache); // Disable rhythm mode
	}

	mRhythmMode = mode;
}
//---------------------------------------------------------
void CVisPlayer::set_note(int const voice, int const note)
{
	if ((voice < kBassDrumChannel) || !mRhythmMode)
	{
		set_note_melodic(voice, note);
	}
	else
	{
		set_note_percussive(voice, note);
	}
}
//---------------------------------------------------------
void CVisPlayer::note_on(int const voice, int const note)
{
	set_note(voice, note + kSilenceNote);
}
//---------------------------------------------------------
void CVisPlayer::note_off(int const voice)
{
	set_note(voice, kSilenceNote);
}
//---------------------------------------------------------
void CVisPlayer::set_note_percussive(int const voice, int const note)
{
	int const channel_bit_mask = 1 << (4-voice+kBassDrumChannel);
	mAMVibRhythmCache &= ~channel_bit_mask;
	opl->write(skOPL2_AmVibRhythmBaseAddress, mAMVibRhythmCache);
	mKeyOnCache[voice] = false;

	if (note != kSilenceNote)
	{
		switch(voice)
		{
			case kTomtomChannel:
				set_freq(kTomtomChannel, note);
				set_freq(kSnareDrumChannel, note + kTomTomToSnare);
				break;
			case kBassDrumChannel:
				set_freq(voice, note);
				break;
			default:
				// Does nothing
				break;
		}

		mKeyOnCache[voice] = true;
		mAMVibRhythmCache |= channel_bit_mask;
		opl->write(skOPL2_AmVibRhythmBaseAddress, mAMVibRhythmCache);
	}
}
//---------------------------------------------------------
void CVisPlayer::set_note_melodic(int const voice, int const note) {
	if (voice >= kNumMelodicVoices)
	{
		DBPRINT("COMPOSER: set_note_melodic() voice " << voice << " >= " << kNumMelodicVoices);
		return;
	}
	opl->write(skOPL2_KeyOnFreqHiBaseAddress + voice, mKOnOctFNumCache[voice] & ~skOPL2_KeyOnMask);
	mKeyOnCache[voice] = false;

	if (note != kSilenceNote)
	{
		set_freq(voice, note, true);
	}
}
//---------------------------------------------------------
void CVisPlayer::set_pitch_range(uint8_t pitchRange) {
	if (pitchRange > 12)
		pitchRange = 12;
	if (pitchRange < 1)
		pitchRange = 1;
	mPitchRangeStep = pitchRange * skNrStepPitch;
}
//---------------------------------------------------------
// From Adlib Music SDK's ADLIB.C ...
void CVisPlayer::change_pitch(int voice, uint16_t const pitchBend) {
	int32_t const pitchBendLength = (int32_t)(pitchBend - kMidPitch) * mPitchRangeStep;

	if ((voice >= kBassDrumChannel) && mRhythmMode)
	{
		return;
	}

	if (mOldPitchBendLength == pitchBendLength)
	{
		// optimisation ...
		mFNumFreqPtrList[voice] = mpOldFNumFreqPtr;
		mHalfToneOffset[voice] = mOldHalfToneOffset;
	}
	else
	{
		int16_t const pitchStepDir = pitchBendLength / kMidPitch;
		int16_t delta;
		if (pitchStepDir < 0)
		{
			int16_t const pitchStepDown = skNrStepPitch - 1 - pitchStepDir;
			mOldHalfToneOffset = mHalfToneOffset[voice] = -(pitchStepDown / skNrStepPitch);
			delta = (pitchStepDown - skNrStepPitch + 1) % skNrStepPitch;
			if (delta)
			{
				delta = skNrStepPitch - delta;
			}
		}
		else
		{
			mOldHalfToneOffset = mHalfToneOffset[voice] = pitchStepDir / skNrStepPitch;
			delta = pitchStepDir % skNrStepPitch;
		}
		mpOldFNumFreqPtr = mFNumFreqPtrList[voice] = skFNumNotes[delta];
		mOldPitchBendLength = pitchBendLength;
	}

	set_freq(voice, mNoteCache[voice], mKeyOnCache[voice]);
}
//---------------------------------------------------------
void CVisPlayer::set_freq(int const voice, int const note, bool const keyOn) {
	int const biased_note = std::max(0, std::min((skMaxNotes-1), note + mHalfToneOffset[voice]));

	uint16_t const frequency = *(mFNumFreqPtrList[voice] + skNoteIndex[biased_note]);

	mNoteCache[voice] = note;
	mKeyOnCache[voice] = keyOn;

	mKOnOctFNumCache[voice] = (skNoteOctave[biased_note] << skOPL2_BlockNumberShift) | ((frequency >> skOPL2_FNumMSBShift) & skOPL2_FNumMSBMask);

	opl->write(skOPL2_FreqLoBaseAddress + voice, frequency & skOPL2_FNumLSBMask);
	opl->write(skOPL2_KeyOnFreqHiBaseAddress + voice, mKOnOctFNumCache[voice] | (keyOn ? skOPL2_KeyOnMask : 0x0));
}
//---------------------------------------------------------
uint8_t CVisPlayer::get_ksltl(const int voice, const uint8_t volume, const int carrier_ksltl) {
	uint16_t kslTL = skOPL2_TLMinLevel - (mKSLTLCache[voice] & skOPL2_TLMask); // amplitude

	kslTL = mVolumeCache[voice] * kslTL;
	kslTL += kslTL + kMaxVolume; // round off to 0.5
	kslTL = skOPL2_TLMinLevel - (kslTL / (2 * kMaxVolume));

	kslTL |= mKSLTLCache[voice] & skOPL2_KSLMask;

	return static_cast<uint8_t>(kslTL);
}
//---------------------------------------------------------
void CVisPlayer::set_volume(int const voice, const uint8_t volume) {
	if (voice >= kNumMelodicVoices && !mRhythmMode)
	{
		DBPRINT("COMPOSER: set_volume() !mRhythmMode voice " << voice << " >= " << kNumMelodicVoices);
		return;
	}
	uint8_t const op_offset = (voice < kSnareDrumChannel || !mRhythmMode) ? op_table[voice] + skCarrierOpOffset : drum_op_table[voice - kSnareDrumChannel];
	mVolumeCache[voice] = volume;
	opl->write(skOPL2_KSLTLBaseAddress + op_offset, get_ksltl(voice, volume, 0));
}
//---------------------------------------------------------
void CVisPlayer::set_instrument(const int voice, const Instrument* instrument) {
	if (instrument == nullptr) {
		instrument = &Instrument::default_instrument;
	}
	const OPLFM& c = instrument->carrier;
	const OPLFM& m = instrument->modulator;
	if ((voice < kSnareDrumChannel) || !mRhythmMode) {
		if (voice >= kNumMelodicVoices) {
			DBPRINT("COMPOSER: set_instrument() !mRhythmMode voice " << voice << " >= " << kNumMelodicVoices);
			return;
		}
		uint8_t const op_offset = op_table[voice];

		opl->write(skOPL2_AaMultiBaseAddress  + op_offset, m.reg20());
		opl->write(skOPL2_KSLTLBaseAddress    + op_offset, m.reg40());
		opl->write(skOPL2_ArDrBaseAddress     + op_offset, m.reg60());
		opl->write(skOPL2_SlrrBaseAddress     + op_offset, m.reg80());
		opl->write(skOPL2_FeedConBaseAddress  + voice    , m.regC0());
		opl->write(skOPL2_WaveformBaseAddress + op_offset, m.regE0());

		mKSLTLCache[voice] = c.reg40();

		opl->write(skOPL2_AaMultiBaseAddress  + op_offset + skCarrierOpOffset, c.reg20());
		//opl->write(skOPL2_KSLTLBaseAddress    + op_offset + skCarrierOpOffset, c.reg40());
		opl->write(skOPL2_KSLTLBaseAddress    + op_offset + skCarrierOpOffset, get_ksltl(voice, 0, 0));
		opl->write(skOPL2_ArDrBaseAddress     + op_offset + skCarrierOpOffset, c.reg60());
		opl->write(skOPL2_SlrrBaseAddress     + op_offset + skCarrierOpOffset, c.reg80());
		opl->write(skOPL2_WaveformBaseAddress + op_offset + skCarrierOpOffset, c.regE0());
	}
	else {
		const uint8_t op_offset = drum_op_table[voice-kSnareDrumChannel];
		mKSLTLCache[voice] = m.reg40();

		opl->write(skOPL2_AaMultiBaseAddress  + op_offset, m.reg20());
		opl->write(skOPL2_KSLTLBaseAddress    + op_offset, get_ksltl(voice, 0, 0));
		opl->write(skOPL2_ArDrBaseAddress     + op_offset, m.reg60());
		opl->write(skOPL2_SlrrBaseAddress     + op_offset, m.reg80());
		//opl->write(skOPL2_FeedConBaseAddress  + voice    , m.regC0()); // TODO: Check if this should be uncommented.
		opl->write(skOPL2_WaveformBaseAddress + op_offset, m.regE0());
	}
}